// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6xwQAWkPYMflyoJr1d-jK9QBWc187Ako',
    appId: '1:686586125525:web:805957dc183eb82e3d965c',
    messagingSenderId: '686586125525',
    projectId: 'myapp-81b37',
    authDomain: 'myapp-81b37.firebaseapp.com',
    storageBucket: 'myapp-81b37.appspot.com',
    measurementId: 'G-8BLLE8SVT1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8AIDzzjtUJWUfebp09nHxK58q2XJvyTA',
    appId: '1:686586125525:android:613980c53f479db83d965c',
    messagingSenderId: '686586125525',
    projectId: 'myapp-81b37',
    storageBucket: 'myapp-81b37.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUKVpAIZEO92CqAIbfOJa3-V-W2O2QHw4',
    appId: '1:686586125525:ios:e052cdff119d20573d965c',
    messagingSenderId: '686586125525',
    projectId: 'myapp-81b37',
    storageBucket: 'myapp-81b37.appspot.com',
    iosClientId: '686586125525-in9h82ijc7kjv8inga8qdp9m2dvf2lgb.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUKVpAIZEO92CqAIbfOJa3-V-W2O2QHw4',
    appId: '1:686586125525:ios:e052cdff119d20573d965c',
    messagingSenderId: '686586125525',
    projectId: 'myapp-81b37',
    storageBucket: 'myapp-81b37.appspot.com',
    iosClientId: '686586125525-in9h82ijc7kjv8inga8qdp9m2dvf2lgb.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
